### ISSUE TITLE
redis 有主备的场合 只能连接到备[slave]的信息, 主[master]的信息无法连接?

### ISSUE THREAD

**Issue by IceiceFire** [NetEaseGame/redis-monitor#1]
redis 有主备的场合 只能连接到备[slave]的信息, 主[master]的信息无法连接?

求帮助

**Comment by hustcc** [comment]
目前是通过 `redis info` 来获取数据，好像仅仅只有 slave 的信息。这个后续我在审查一下，因为不同版本 redis 这个返回数据还不一样，兼容和测试都挺麻烦的。

**Comment by IceiceFire** [comment]
thank you
