### ISSUE TITLE
求助，执行pip install -r requirements.txt命令之后，出现如下报错提示。

### ISSUE THREAD

**Issue by xhz-bza** [NetEaseGame/redis-monitor#2]
```py
File "<string>", line 1, in <module>
      File "/tmp/pip-build-NUlvFB/sqlite3/setup.py", line 2, in <module>
        raise RuntimeError("Package 'sqlite3' must not be downloaded from pypi")
    RuntimeError: Package 'sqlite3' must not be downloaded from pypi
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NUlvFB/sqlite3/
```

**Comment by hustcc** [comment]
你直接运行 python run_monitor.py 试试，然后缺什么，就 pip 安装什么。

**Comment by xhz-bza** [comment]
# python run_monitor.py 
Traceback (most recent call last):
  File "run_monitor.py", line 8, in <module>
    from app import app
  File "/root/redis-monitor/app/__init__.py", line 7, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by xhz-bza** [comment]
pip install redis，是什么意思呢？是在监控主机装redis模块还是装redis包啊。

还有个问题就是哪里能看到标识master、slave状态么？

可以设置开机启动么？

**Comment by xhz-bza** [comment]
我装的怎么没看见Flush DB这个按钮呢？奇怪了

**Comment by hustcc** [comment]
pip install redis 是安装 redis 连接的 py 库。

master slave 是看redis的连接方式，Flush DB只有在 redis db中有数据的时候才会出现，否则就是没有的啊。

开机启动是操作系统的事情，和这个应用没有关系，可以自行设置。

**Comment by xhz-bza** [comment]
在哪看连接方式？db中有数据的啊，key=value，type是string类型的啊。

**Comment by hustcc** [comment]
在 redis.conf 中可以配置 redis 的 master 和 slave。

**Comment by hustcc** [comment]
已经重构，现在只需要使用  `pip install redis-monitor` 就可以把这个安装好了。

然后 `redis-monitor init` 初始化配置；

最后 `redis-monitor start` 就可以开启服务了。
