### ISSUE TITLE
怎么使用这个工具呢

### ISSUE THREAD

**Issue by 1009043828** [NetEaseGame/redis-monitor#5]
我已经安装好了，并且运行了第三步了，在哪里配置redis的ip端口和密码呢，浏览器中是空白的，左上角只有一只小猫

**Comment by hustcc** [comment]
F12 看看浏览器有什么报错吗？之前也有人报这个问题，但是确定是他系统环境的问题。

正常情况，页面打开之后，可以填写 ip port 密码，然后就添加一个 redis 监控实例。

**Comment by 1009043828** [comment]
![1](https://cloud.githubusercontent.com/assets/22495163/23685207/cf4024ac-03dd-11e7-9869-299a98fba97e.png)
![2](https://cloud.githubusercontent.com/assets/22495163/23685206/ced7116a-03dd-11e7-9538-b14250f16ceb.png)
![3](https://cloud.githubusercontent.com/assets/22495163/23685208/d01daeda-03dd-11e7-87e5-b195960469de.png)
我截了图，请问一下这些有异常么？

**Comment by hustcc** [comment]
https://127.0.0.1:9527/static/dist/redis-minitor.bundle.js 这个js文件可以打开吗？

**Comment by 1009043828** [comment]
打不开呢

**Comment by hustcc** [comment]
上面的网址输入错了，这个地址：[http://127.0.0.1:9527/static/dist/redis-moinitor.bundle.js](http://127.0.0.1:9527/static/dist/redis-moinitor.bundle.js)

**Comment by 1009043828** [comment]
直接404了

**Comment by 1009043828** [comment]
我是直接把源码下下来用setup.py安装的，会有不一样么

**Comment by hustcc** [comment]
你可以试试看，或者直接下载下面，然后使用:

```py
python manage.py init

python manage.py createdb

python manage.py start
```

这样试试看。

很奇怪，我用 pip install redis-monitor 安装，在好几台机器都是可以运行的。

**Comment by fq47523** [comment]
如果是把源码下下来用setup.py安装的，这个时候好多对象无法初始化，但可以运行，会出现404.
请清理你的环境使用python2.7以上，或者env，使用PIP安装后就可以了

**Comment by hustcc** [comment]
对象无法初始化是什么意思？

**Comment by fq47523** [comment]
报的什么错，没有留意呢，误以为setup.py，直接安装。

**Comment by hustcc** [comment]
@fq47523 安装没有报错，但是打开网页前端，js 文件找不到。

**Comment by fq47523** [comment]
@hustcc    他：【我是直接把源码下下来用setup.py安装的，会有不一样么。】
他这个时候的环境已经有问题了，如果pip在次安装，就会出现可以打开网页前端，js 文件找不到。

**Comment by fq47523** [comment]
@hustcc    我的环境是centos7+python3.5.2  PIP安装

**Comment by hustcc** [comment]
python 3 我米有测试过，我测试的环境都是 Python 2 。

**Comment by fq47523** [comment]
源码打包下载安装的方法是不是这个？
python manage.py init

python manage.py createdb

python manage.py start

**Comment by hustcc** [comment]
是的

**Comment by hustcc** [comment]
@1009043828 我这里没有 py3 环境，原因应该就是 python 3 下面 static 资源找不到。

帮我测试一下吧：

```
pip install redis-monitor==1.0.2.dev0

redis-monitor start
```

看看能不能正常打开。

**Comment by 1009043828** [comment]
我用的py2.7.6的，可以正常打开了， @hustcc ，谢谢二位啦 @hustcc @fq47523

**Comment by hustcc** [comment]
帮我在py3下测试下呗😊

**Comment by 1009043828** [comment]
py3也可以用哈
