### ISSUE TITLE
问：windows server环境下，redis-monitor.bundle.js无法加载

### ISSUE THREAD

**Issue by bestwiz31** [NetEaseGame/redis-monitor#8]
Linux环境下可以正常加载，页面显示和监控都正常，windows server环境下，init,createdb,start都没错误，但是redis-monitor.bundle.js加载显示404，画面不正常，有遇到过这个问题吗，还是环境的事？

**Comment by hustcc** [comment]
求截图！

**Comment by bestwiz31** [comment]
![pic1](https://user-images.githubusercontent.com/32257952/30801874-56615ffa-a217-11e7-93b2-f2590a07c042.png)
C:\Python27\Lib\site-packages\app\static\dist 路径下是有这个js文件的

**Comment by bestwiz31** [comment]
redis-monitor version 1.0.3

**Comment by bestwiz31** [comment]
用非正常手段终于运行起来了，能介绍下监控画面4张图的含义吗？

**Comment by hustcc** [comment]
请看 readme…😂
